source 'https://github.com/CocoaPods/Specs.git'

target 'OGRSAEncryption', :exclusive => true do
  pod "OGRSAEncryption", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "OGRSAEncryption", :path => "../"

  
end
